export const TIMER_SETTINGS_LOADING = 'TIMER_SETTINGS_LOADING';
export const TIMER_SETTINGS_FAIL = 'TIMER_SETTINGS_FAIL';
export const TIMER_SETTINGS_SUCCESS = 'TIMER_SETTINGS_SUCCESS';
export const TIMER_SETTINGS_RESET = 'TIMER_SETTINGS_RESET';

export const GET_SETTINGS_LOADING = 'GET_SETTINGS_LOADING';
export const GET_SETTINGS_FAIL = 'GET_SETTINGS_FAIL';
export const GET_SETTINGS_SUCCESS= 'GET_SETTINGS_SUCCESS';



